import React from 'react';
import Navigation from './components/Navigation';
import Section from './components/Section';
import CodeBlock from './components/CodeBlock';
import { 
  AlertTriangle, 
  Clock, 
  Settings, 
  Key, 
  ArrowRight,
  Mail,
  Cloud,
  Calendar,
  CheckCircle,
  Terminal,
  UserCheck
} from 'lucide-react';

const App: React.FC = () => {
  
  const psScript = `# PowerShell Runbook: Check-AppRegistrationSecrets
# Required Modules: 
#   - Microsoft.Graph.Authentication
#   - Microsoft.Graph.Applications
#   - Microsoft.Graph.Users.Actions (Required for Send-MgUserMail)

param(
    # IMPORTANT: The Managed Identity must have 'Mail.Send' permission
    # and this mailbox must exist in your tenant.
    [string]$SenderMailbox = "automation-alerts@contoso.com",
    
    # Who receives the alerts?
    [string]$RecipientEmail = "admin-team@contoso.com"
)

$ErrorActionPreference = "Stop"

try {
    # 1. Connect to Graph using Managed Identity
    Write-Output "Connecting to Microsoft Graph..."
    Connect-MgGraph -Identity
    
    # 2. Get all applications with secrets
    # We fetch all apps to ensure we don't miss any.
    $apps = Get-MgApplication -All -Property DisplayName, AppId, PasswordCredentials

    $alertItems = @()

    foreach ($app in $apps) {
        foreach ($secret in $app.PasswordCredentials) {
            $expiryDate = $secret.EndDateTime
            
            # Check if secret has an expiry date
            if ($null -ne $expiryDate) {
                $daysLeft = ($expiryDate - (Get-Date)).Days

                # 3. Check for specific notification windows: 60, 30, or 7 days
                # This ensures we don't spam users daily, only on specific milestones.
                if ($daysLeft -eq 60 -or $daysLeft -eq 30 -or $daysLeft -eq 7) {
                    
                    $priority = "Warning"
                    if ($daysLeft -le 7) { $priority = "URGENT" }
                    
                    $alertItems += [PSCustomObject]@{
                        AppName = $app.DisplayName
                        AppId = $app.AppId
                        DaysLeft = $daysLeft
                        Priority = $priority
                        ExpiresOn = $expiryDate.ToString("yyyy-MM-dd")
                    }
                    
                    Write-Output "DETECTED: $($app.DisplayName) expires in $daysLeft days."
                }
            }
        }
    }

    # 4. Send Email if expiring secrets found
    if ($alertItems.Count -gt 0) {
        Write-Output "Sending alert email to $RecipientEmail..."
        
        # Build HTML Table
        $tableRows = ""
        foreach ($item in $alertItems) {
            # Highlight urgent items in red
            $color = if ($item.DaysLeft -le 7) { "#ffebee" } else { "#ffffff" }
            $tableRows += "<tr style='background-color:$color'><td>$($item.AppName)</td><td>$($item.AppId)</td><td><strong>$($item.DaysLeft)</strong></td><td>$($item.ExpiresOn)</td></tr>"
        }

        $htmlBody = @"
        <div style="font-family: Segoe UI, sans-serif;">
            <h3 style="color:#0078D4">Azure App Secret Expiry Alert</h3>
            <p>The following application secrets are approaching expiration:</p>
            <table border='1' cellpadding='10' style='border-collapse:collapse; border:1px solid #ddd; width:100%;'>
                <tr style='background-color:#f8f9fa; text-align:left;'><th>App Name</th><th>App ID</th><th>Days Left</th><th>Expiry Date</th></tr>
                $tableRows
            </table>
            <br/>
            <p><strong>Action Required:</strong> Please rotate these secrets immediately to prevent production outages.</p>
            <p style="color:#666; font-size:12px;">Generated by Azure Automation | 60-30-7 Day Monitor</p>
        </div>
"@

        $params = @{
            Message = @{
                Subject = "[ACTION REQUIRED] Azure Secrets Expiring ($($alertItems.Count) Apps)"
                Body = @{
                    ContentType = "HTML"
                    Content = $htmlBody
                }
                ToRecipients = @(
                    @{ EmailAddress = @{ Address = $RecipientEmail } }
                )
            }
            SaveToSentItems = $false
        }

        # Send using the Sender Mailbox
        # The Managed Identity acts on behalf of this mailbox.
        Send-MgUserMail -UserId $SenderMailbox -BodyParameter $params
        
        Write-Output "Email sent successfully."
    } else {
        Write-Output "No secrets found expiring specifically at 60, 30, or 7 days today."
    }

} catch {
    Write-Error "An error occurred: $_"
}`;

  const permissionScript = `# RUN THIS LOCALLY (One-time setup)
# This script grants the Managed Identity permission to:
# 1. Read all App Registrations (Application.Read.All)
# 2. Send emails as ANY user (Mail.Send) - Use with caution!

$TenantId = "your-tenant-id"
# Get this Object ID from the Automation Account -> Identity blade
$ManagedIdentityObjectId = "paste-object-id-of-managed-identity-here"

Connect-MgGraph -TenantId $TenantId -Scopes "AppRoleAssignment.ReadWrite.All", "Application.Read.All"

$GraphAppId = "00000003-0000-0000-c000-000000000000" # Microsoft Graph Service Principal

# 1. Grant Application.Read.All
$AppReadRole = Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $GraphAppId | 
               Where-Object {$_.Value -eq "Application.Read.All"} 

New-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $ManagedIdentityObjectId -PrincipalId $ManagedIdentityObjectId -ResourceId $GraphAppId -AppRoleId $AppReadRole.Id

# 2. Grant Mail.Send
# This allows the automation account to send mail via Send-MgUserMail
$MailSendRole = Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $GraphAppId | 
                Where-Object {$_.Value -eq "Mail.Send"}

New-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $ManagedIdentityObjectId -PrincipalId $ManagedIdentityObjectId -ResourceId $GraphAppId -AppRoleId $MailSendRole.Id

Write-Host "Permissions assigned successfully."`;

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 font-sans">
      <Navigation />

      {/* Hero Section */}
      <header className="bg-gradient-to-r from-[#0078D4] to-[#004e8c] text-white py-20 lg:py-28 relative overflow-hidden">
        {/* Abstract shapes/bg decoration */}
        <div className="absolute top-0 right-0 -mt-20 -mr-20 w-80 h-80 bg-blue-500 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob"></div>
        <div className="absolute bottom-0 left-0 -mb-20 -ml-20 w-80 h-80 bg-indigo-500 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob animation-delay-2000"></div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="lg:w-2/3">
            <div className="inline-flex items-center gap-2 bg-blue-800 bg-opacity-40 border border-blue-400 border-opacity-30 rounded-full px-4 py-1.5 mb-8 backdrop-blur-sm">
              <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse"></span>
              <span className="text-xs font-semibold tracking-wide uppercase text-blue-50">Updated for Graph API</span>
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight mb-6 leading-tight">
              Never Let a Secret <br/>Expire Again
            </h1>
            <p className="text-xl text-blue-100 mb-8 leading-relaxed max-w-2xl">
              Automate client secret monitoring with Azure Automation. Receive email alerts <strong>60, 30, and 7 days</strong> before expiration to prevent production outages.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <a href="#step-by-step" className="inline-flex items-center justify-center bg-white text-[#0078D4] hover:bg-gray-100 px-8 py-4 rounded-lg font-bold shadow-lg transition-all hover:shadow-xl transform hover:-translate-y-1 text-lg">
                Start Setup
                <ArrowRight className="ml-2 h-5 w-5" />
              </a>
              <a href="#scripts" className="inline-flex items-center justify-center bg-[#0078D4] border-2 border-white/30 hover:bg-[#006cbd] text-white px-8 py-4 rounded-lg font-bold transition-all backdrop-blur-sm text-lg">
                <Terminal className="mr-2 h-5 w-5" />
                Get Scripts
              </a>
            </div>
          </div>
        </div>
      </header>

      {/* Overview Section */}
      <Section id="overview" title="Proactive Monitoring Strategy">
        <div className="grid md:grid-cols-3 gap-8 mt-12">
          <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100 hover:border-[#0078D4] transition-all group">
            <div className="h-14 w-14 bg-red-50 text-red-600 rounded-2xl flex items-center justify-center mb-6 group-hover:bg-red-600 group-hover:text-white transition-colors">
              <AlertTriangle className="h-7 w-7" />
            </div>
            <h3 className="text-xl font-bold mb-3">The Problem</h3>
            <p className="text-gray-600 leading-relaxed">
              App Registration secrets have a hard expiry. When they die, your app dies. Manual calendar reminders are fragile and easily missed by human operators.
            </p>
          </div>
          
          <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100 hover:border-[#0078D4] transition-all group">
            <div className="h-14 w-14 bg-blue-50 text-[#0078D4] rounded-2xl flex items-center justify-center mb-6 group-hover:bg-[#0078D4] group-hover:text-white transition-colors">
              <Calendar className="h-7 w-7" />
            </div>
            <h3 className="text-xl font-bold mb-3">The Cadence</h3>
            <p className="text-gray-600 leading-relaxed">
              We implement a rigid notification schedule. You will receive alerts exactly <strong>60 days</strong> (planning), <strong>30 days</strong> (warning), and <strong>7 days</strong> (critical) before expiration.
            </p>
          </div>

          <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100 hover:border-[#0078D4] transition-all group">
            <div className="h-14 w-14 bg-green-50 text-green-600 rounded-2xl flex items-center justify-center mb-6 group-hover:bg-green-600 group-hover:text-white transition-colors">
              <Mail className="h-7 w-7" />
            </div>
            <h3 className="text-xl font-bold mb-3">The Delivery</h3>
            <p className="text-gray-600 leading-relaxed">
              Alerts are delivered via HTML email to your team's mailbox or ticketing system. The email identifies the specific app, App ID, and exact expiry date.
            </p>
          </div>
        </div>
      </Section>

      {/* How It Works Section */}
      <Section id="how-it-works" title="Architecture" dark>
        <div className="flex flex-col lg:flex-row items-center justify-center gap-16 mt-8">
          
          <div className="w-full lg:w-1/2 bg-white p-10 rounded-2xl shadow-xl border border-gray-200">
             <h4 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-8 flex items-center gap-2">
                <Settings className="w-4 h-4" /> Automation Flow
             </h4>
             <div className="space-y-0 relative">
                {/* Connecting Line */}
                <div className="absolute left-6 top-6 bottom-6 w-0.5 bg-gray-100"></div>

                {/* Step 1 */}
                <div className="relative flex items-start gap-6 pb-12">
                   <div className="z-10 flex-shrink-0 h-12 w-12 bg-[#0078D4] rounded-full flex items-center justify-center text-white shadow-lg ring-4 ring-white">
                      <Clock className="w-6 h-6" />
                   </div>
                   <div>
                      <h4 className="text-lg font-bold text-gray-900">Daily Trigger</h4>
                      <p className="text-sm text-gray-500 mt-1">Azure Automation Schedule</p>
                      <p className="text-gray-600 mt-2">The runbook executes once every 24 hours to scan the tenant.</p>
                   </div>
                </div>

                {/* Step 2 */}
                <div className="relative flex items-start gap-6 pb-12">
                   <div className="z-10 flex-shrink-0 h-12 w-12 bg-white border-2 border-[#0078D4] rounded-full flex items-center justify-center text-[#0078D4] shadow-sm ring-4 ring-white">
                      <Key className="w-6 h-6" />
                   </div>
                   <div>
                      <h4 className="text-lg font-bold text-gray-900">Secret Inspection</h4>
                      <p className="text-sm text-gray-500 mt-1">Managed Identity + Graph API</p>
                      <p className="text-gray-600 mt-2">Script authenticates and pulls expiry dates for all apps using <code>Application.Read.All</code>.</p>
                   </div>
                </div>

                {/* Step 3 */}
                <div className="relative flex items-start gap-6">
                   <div className="z-10 flex-shrink-0 h-12 w-12 bg-green-500 rounded-full flex items-center justify-center text-white shadow-lg ring-4 ring-white">
                      <Mail className="w-6 h-6" />
                   </div>
                   <div>
                      <h4 className="text-lg font-bold text-gray-900">Mailbox Alert</h4>
                      <p className="text-sm text-gray-500 mt-1">Send-MgUserMail</p>
                      <p className="text-gray-600 mt-2">If 60/30/7 days remain, an email is sent FROM your automation mailbox TO your operations team.</p>
                   </div>
                </div>
             </div>
          </div>

          <div className="w-full lg:w-1/3 space-y-6">
              <h3 className="text-2xl font-bold text-gray-900">Secure by Design</h3>
              <p className="text-gray-600">
                  This solution uses <strong>Managed Identities</strong>, meaning:
              </p>
              <ul className="space-y-4">
                  <li className="flex items-start gap-3">
                      <CheckCircle className="w-6 h-6 text-green-500 flex-shrink-0" />
                      <span className="text-gray-700">No hardcoded client secrets in scripts</span>
                  </li>
                  <li className="flex items-start gap-3">
                      <CheckCircle className="w-6 h-6 text-green-500 flex-shrink-0" />
                      <span className="text-gray-700">No username/password storage</span>
                  </li>
                  <li className="flex items-start gap-3">
                      <CheckCircle className="w-6 h-6 text-green-500 flex-shrink-0" />
                      <span className="text-gray-700">Granular Graph API permissions</span>
                  </li>
              </ul>
          </div>

        </div>
      </Section>

      {/* Step by Step Guide */}
      <Section id="step-by-step" title="Detailed Setup Guide">
        <div className="space-y-16 mt-8 max-w-4xl mx-auto">
            
            {/* Step 1 */}
            <div className="flex gap-6">
                <div className="flex-shrink-0">
                    <span className="flex items-center justify-center w-12 h-12 rounded-full border-2 border-gray-200 font-bold text-gray-500 bg-white">1</span>
                </div>
                <div className="flex-grow">
                    <h3 className="text-2xl font-bold text-gray-900 mb-4">Create Automation Account</h3>
                    <p className="text-gray-600 mb-4">
                        1. Go to Azure Portal → Search <strong>"Automation Accounts"</strong> → Create.<br/>
                        2. Select your Subscription and Resource Group.<br/>
                        3. <strong>Critical:</strong> Under the "Identity" tab (or Advanced), ensure <strong>System assigned managed identity</strong> is checked/enabled. This identity will be used to run the scripts.
                    </p>
                </div>
            </div>

            {/* Step 2 */}
            <div className="flex gap-6">
                <div className="flex-shrink-0">
                    <span className="flex items-center justify-center w-12 h-12 rounded-full border-2 border-gray-200 font-bold text-gray-500 bg-white">2</span>
                </div>
                <div className="flex-grow">
                    <h3 className="text-2xl font-bold text-gray-900 mb-4">Import PowerShell Modules</h3>
                    <p className="text-gray-600 mb-4">
                        The script relies on the Microsoft Graph SDK. You must import these modules into your Automation Account from the Gallery:
                    </p>
                    <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-4 text-sm text-yellow-800">
                        Go to your Automation Account → Shared Resources → Modules → Add a module → Browse Gallery.
                    </div>
                    <ul className="list-disc list-inside text-gray-700 space-y-2 mb-4 font-mono text-sm bg-gray-50 p-4 rounded-md">
                        <li>Microsoft.Graph.Authentication <span className="text-gray-400 text-xs">(Login)</span></li>
                        <li>Microsoft.Graph.Applications <span className="text-gray-400 text-xs">(Read Apps)</span></li>
                        <li>Microsoft.Graph.Users.Actions <span className="text-gray-400 text-xs">(Send Email)</span></li>
                    </ul>
                    <p className="text-sm text-gray-500">Note: Ensure you select Runtime version 5.1 (or 7.2). Both are supported by these modules.</p>
                </div>
            </div>

            {/* Step 3 */}
            <div className="flex gap-6">
                <div className="flex-shrink-0">
                    <span className="flex items-center justify-center w-12 h-12 rounded-full border-2 border-gray-200 font-bold text-gray-500 bg-white">3</span>
                </div>
                <div className="flex-grow">
                    <h3 className="text-2xl font-bold text-gray-900 mb-4">Assign Graph API Permissions</h3>
                    <p className="text-gray-600 mb-4">
                        The Managed Identity needs permission to read application secrets and send emails. This <strong>cannot</strong> be done in the portal UI; you must run this script locally <strong>once</strong> by an admin.
                    </p>
                    <div className="bg-blue-50 p-4 rounded-md mb-4 text-sm text-blue-800 flex items-start">
                        <UserCheck className="w-5 h-5 mr-2 flex-shrink-0" />
                        <span><strong>Tip:</strong> You need the Object ID of the Automation Account's Managed Identity (found in the Identity blade).</span>
                    </div>
                    <CodeBlock 
                        language="powershell" 
                        title="SetupScript.ps1 - Run locally"
                        code={permissionScript} 
                    />
                </div>
            </div>

             {/* Step 4 */}
             <div className="flex gap-6">
                <div className="flex-shrink-0">
                    <span className="flex items-center justify-center w-12 h-12 rounded-full border-2 border-gray-200 font-bold text-gray-500 bg-white">4</span>
                </div>
                <div className="flex-grow">
                    <h3 className="text-2xl font-bold text-gray-900 mb-4">Create & Configure Runbook</h3>
                    <p className="text-gray-600 mb-4">
                        1. Create a new <strong>PowerShell</strong> Runbook named <code>Monitor-AppSecrets</code>.<br/>
                        2. Paste the script from the "Scripts" section below.<br/>
                        3. <strong>Update Variables:</strong> Look for <code>$SenderMailbox</code> in the script.
                    </p>
                    <div className="bg-red-50 border-l-4 border-red-400 p-4 mb-2 text-sm text-gray-800">
                        <strong>Sender Mailbox Requirement:</strong><br/>
                        The <code>$SenderMailbox</code> variable must be a valid User Mailbox or Shared Mailbox in your tenant. The <code>Mail.Send</code> permission allows the Managed Identity to impersonate this user to send the alert.
                    </div>
                </div>
            </div>

            {/* Step 5 */}
             <div className="flex gap-6">
                <div className="flex-shrink-0">
                    <span className="flex items-center justify-center w-12 h-12 rounded-full border-2 border-gray-200 font-bold text-gray-500 bg-white">5</span>
                </div>
                <div className="flex-grow">
                    <h3 className="text-2xl font-bold text-gray-900 mb-4">Schedule the Runbook</h3>
                    <p className="text-gray-600 mb-4">
                        To ensure the 60, 30, and 7-day triggers fire on the correct day, the script must run daily.
                    </p>
                    <ul className="list-disc list-inside text-gray-600 bg-gray-50 p-4 rounded-lg border border-gray-100">
                        <li>In the Runbook, click <strong>Schedules</strong> → Add a schedule.</li>
                        <li>Create a new schedule: "Daily-6AM".</li>
                        <li>Recurrence: <strong>Daily</strong>.</li>
                        <li>Link it to your runbook.</li>
                    </ul>
                </div>
            </div>

        </div>
      </Section>

      {/* Scripts Section */}
      <Section id="scripts" title="Production Script" subtitle="Copy, paste, and configure variables." dark>
        <div className="max-w-4xl mx-auto">
            <div className="bg-blue-50 border-l-4 border-[#0078D4] p-4 mb-6">
                <div className="flex">
                    <div className="flex-shrink-0">
                        <Terminal className="h-5 w-5 text-[#0078D4]" />
                    </div>
                    <div className="ml-3">
                        <p className="text-sm text-blue-700">
                            <strong>Note:</strong> Update <code>$SenderMailbox</code> and <code>$RecipientEmail</code> at the top of the script before publishing.
                        </p>
                    </div>
                </div>
            </div>
            <CodeBlock 
                language="powershell" 
                code={psScript} 
                title="Runbook: Monitor-AppSecrets.ps1" 
            />
        </div>
      </Section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 py-12 border-t border-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid md:grid-cols-3 gap-8 mb-8">
                <div>
                    <div className="flex items-center text-white mb-4">
                        <Cloud className="h-6 w-6 mr-2 text-[#0078D4]" />
                        <span className="font-bold text-lg">AzureOpsAuto</span>
                    </div>
                    <p className="text-sm text-gray-500">
                        Simplifying Azure governance one script at a time.
                    </p>
                </div>
                <div>
                    <h4 className="text-white font-semibold mb-4">Docs</h4>
                    <ul className="space-y-2 text-sm">
                        <li><a href="https://learn.microsoft.com/en-us/graph/api/user-sendmail" className="hover:text-white transition-colors">Graph API: Send Mail</a></li>
                        <li><a href="https://learn.microsoft.com/en-us/azure/automation/automation-intro" className="hover:text-white transition-colors">Azure Automation Overview</a></li>
                    </ul>
                </div>
                <div>
                    <h4 className="text-white font-semibold mb-4">Support</h4>
                    <div className="flex items-center gap-2 text-sm">
                        <Mail className="h-4 w-4" />
                        <span className="text-gray-500">support@example.com</span>
                    </div>
                </div>
            </div>
            <div className="border-t border-gray-800 pt-8 text-center text-sm">
                &copy; {new Date().getFullYear()} AzureOpsAuto. Not affiliated with Microsoft.
            </div>
        </div>
      </footer>
    </div>
  );
};

export default App;